[package]
name = "smt-nocture-db-to-rdf"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
csv = "1.3.0"
lazy_static = "1.5.0"
serde = {version="1.0.209", features=["derive"]}
sophia_api = "0.8.0"
sophia_turtle = "0.8.0"
